context:
  version: "0.6.0"

package:
  name: llama-index-vector-stores-qdrant
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/llama-index-vector-stores-qdrant/llama_index_vector_stores_qdrant-${{ version }}.tar.gz
    sha256: f2f06710e5fa39be1c5f14287e6bb124166e9b1745ba0f3c2611add549ee006b
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core
  run:
    - python >=${{ python_min }}
    - qdrant-client >=1.7.1
    - grpcio <2.0.0,>=1.60.0
    - llama-index-core <0.13.0,>=0.12.7

tests:
  - python:
      imports:
        - llama_index.vector_stores.qdrant
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/run-llama/llama_index
  repository: https://github.com/run-llama/llama_index
  summary: llama-index vector_stores qdrant integration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
